### ISSUE TITLE
"Missing OS"

### ISSUE THREAD

**Issue by 0xCTF** [imperador/chromefy#107]
I got "Missing OS" after successful installation
please help urgently, it's for a client's laptop

**Comment by dragon788** [comment]
I would HIGHLY recommend *NOT* installing Chromefy on systems that you do not own. There is a legal liability issue you are exposing your client to because several components of ChromeOS are licensed and while you might be open to taking that risk, your client probably has very little knowledge of the potential repercussions.

**Comment by waskywabbit719** [comment]
i agree with dragon788 and understand his point entirely, however i would like to know if there is any info or advice to the initial issue referenced? (the "Missing OS")
i have encountered this issue as well (on my own machine), after succesful install (using the "option 1" method) and am trying to understand why.
any insight would be appreciated! thank you in advance.

**Comment by dragon788** [comment]
Check the comments on other issues, but I'd imagine that it didn't properly complete the installation and you need the fixed EFI and ROOT partition sizes in the install script.
