### ISSUE TITLE
Google Play Service and Linux emulation doesn't work

### ISSUE THREAD

**Issue by flifloo** [imperador/chromefy#13]
I installed Chrome OS with Chromefy on my computer with dual boot (Ubuntu).
No problems with the installation, I follow all the Google Docs.
When the OS boot (after the grub root path problem) Google Play service get an error on configuration and Linux emulator setup get also an error.
What can I do ?
(PS : I had other issue like infinite shutdown but I think they had a link between all issues like an error on installation)

**Comment by liberostelios** [comment]
I had the exact same issues. The problem was I haven't done the installation correctly. A clear sign for this is if you get an issue when running sudo:

```
sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set
```

This happens if your filesystem wasn't copied as it should. What I have done wrong, is that I followed the dual boot guide and ran all the ``cp`` commands with ``sudo`` through a third installation (a Ubuntu) instead of running them on Chromium OS. If that's the case, you end up with a filesystem where another root user owns your base files and that's causing most things to brake (among a few sudo, Android Apps, Linux container and the shutdown process).

The solution, as said, is to do everything through Chromium OS. So, format your ROOT-A again and copy everything when logged in as ``chronos`` from a Chromium OS installation (or USB).

I hope this helps.

**Comment by flifloo** [comment]
I got this error with sudo, thanks you for your help !
I will reinstall with the latest version that is out.
