### ISSUE TITLE
Android apps won't work after reboot

### ISSUE THREAD

**Issue by aggalex** [imperador/chromefy#6]
When I reboot chromefy's Chrome OS I cannot reopen any installed android apps.

**Comment by alesimula** [comment]
Did you use mkfs.ext4 on partition 1 to make a powerwash like the guide says?

**Comment by imperador** [comment]
@aggalex any feedback?

**Comment by MuntashirAkon** [comment]
Similar happened to me. I disabled Play Store and the enabled it again (all data on Android is gone, btw), and it worked.

**Comment by MuntashirAkon** [comment]
Previously I've used @arnoldthebat's 72 release with eve and caroline's 71 releases, which created several problems, including Play Store being stopped working on reboot. (This is due to shutdown-related problem, I believe).

Make sure you're using the *same* versions of @arnoldthebat's Chromium OS, Eve and Caroline or whatever distributions you're using. (I'm using 72 releases)

**Comment by Crescendo-BLYAT** [comment]
ATB72 special + Eve73 is all working except tap-to-click....

**Comment by MuntashirAkon** [comment]
> ATB72 special + Eve73 is all working except tap-to-click....

[See here](https://github.com/arnoldthebat/chromiumos/issues/128#issuecomment-418272523) for tap-to-click solution.

**Comment by imperador** [comment]
No feedbacks about this issue and no problems related to this. Closing the issue

**Comment by Crescendo-BLYAT** [comment]
chiming in here, as for android app unusable after reboot, it's hard to exactly tell why but almost all image I tried except Eve got the same problem....

seems Eve image is the only thing that working right without issue...
