### ISSUE TITLE
What is coming from chromium and what is coming from recovery image?

### ISSUE THREAD

**Issue by intdel** [imperador/chromefy#65]
Hello,

As I understand when you update you only reflash the recovery image to /dev/sda3. However, which parts do not get updated that way?

I am a bit confused as to why we do not need to update the base chromium image.

Thanks

**Comment by zZSETHzz** [comment]
The base Chromium image is used for its Kernel. The original ChromeOS kernel with limited hardware support is replaced with the one using in the Chromium image. The reason why you only need to update /dev/sda3 is because the kernel is already there and all you need to update is the OS itself and not the underlying kernel.
