### ISSUE TITLE
how do you resize data partition?

### ISSUE THREAD

**Issue by chanhyokpark** [imperador/chromefy#77]
I run chromefy.sh successfully and I installed chromium.img at my USB, but the 
 installer doesn't work so I have to use _dd_ command. it worked, but I have only 4gb data partition. what is the data partition in CrOS and how do you fix it?

 ![Screenshot 2019-06-24 at 7 02 35 AM - Display 1](https://user-images.githubusercontent.com/49719798/59982474-1676a300-964e-11e9-81aa-b7bf4181d362.png)
(sorry I'm korean)

**Comment by chanhyokpark** [comment]
I used GParted and succeed, but is there another solution?

**Comment by dragon788** [comment]
You can't be booted into the ChromeOS you are fixing the STATE partition for (aka user data), but if you are booted from the Chromefy USB you can use a couple tools on the disk to resize or delete the STATE partition and recreate/extend it to fill the rest of the disk. I've found it is easier to delete and recreate, mostly because I'm also editing the size of the ROOT-A partition and having the STATE partition out of the way makes that a lot easier.
