### ISSUE TITLE
Chromefy on a Chromebook

### ISSUE THREAD

**Issue by unapropriate** [imperador/chromefy#9]
I saw some posts over at Reddit about Chromefy on a Chromebook to get Android apps working. I was wondering, how can you install Chromefy on a Chromebook?

**Comment by imperador** [comment]
Try to generate an img with the first method using Pyro recovery image and name it "chromefy.img". Save it on a place where you can get to it from a live usb (and other than your main drive, because it will be erased).

Then you will need a live usb with gparted. Boot from it and close gparted, mount your emmc drive (you can do it from the Terminal). And also make sure that you have the path to your chromefy.img.

Run the following command (I am using an emmc as example):
dd    if=/{your path to chromefy}/chromefy.img     of=/dev/mmcblk0

Wait, it will take some time. After the completion, close the terminal and open Gparted. Delete the last partition (/dev/mmcblk0p1) and then create a new one with all the remaining space. Name it STATE, also put STATE as its label.

Reboot your pc.

**Comment by jpfree** [comment]
> [Not stable yet]
> 
> Try to generate an img with the Method 1 of the guide using Pyro recovery image and name it "chromefy.img". Save it in a place where you can get to it from a live USB (and other than your main drive because it will be erased).
> 
> Then you will need a live USB with gparted. Boot from it and close gparted, mount your emmc drive (you can do it from the Terminal). And also make sure that you have the path to your chromefy.img.
> 
> Run the following command (I am using an emmc as an example):
> dd if=/{your path to chromefy}/chromefy.img of=/dev/mmcblk0
> 
> Wait, it will take some time. After the completion, close the terminal and open Gparted. Delete the last partition (/dev/mmcblk0p1) and then create a new one with all the remaining space. Name it STATE and also put STATE as its label.
> 
> Reboot your pc.

 it need flash mrchromebox's bios first?

whiceh live USB system i can use
